version: '3'
services:

  # Base Images

  php72-fpm-stretch-base:
    build:
      context: ./
      dockerfile: base.Dockerfile
    image: my127/drupal8:7.2-fpm-stretch

  php73-fpm-stretch-base:
    build:
      context: ./
      dockerfile: base.Dockerfile
    image: my127/drupal8:7.3-fpm-stretch


  # Console Images

  php72-fpm-stretch-console:
    build:
      context: ./
      dockerfile: console.Dockerfile
    image: my127/drupal8:7.2-fpm-stretch-console

  php73-fpm-stretch-console:
    build:
      context: ./
      dockerfile: console.Dockerfile
    image: my127/drupal8:7.3-fpm-stretch-console
